[package]
name = "pngme"
version = "0.1.0"
authors = ["artslob <artslob@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
byteorder = "1.4.3"
derive_more = "0.99.14"
clap = "3.0.0-beta.2"
